### ISSUE TITLE
Legacy FCM APIs will be removed in June 2024

### ISSUE THREAD

**Issue by juangvega** [Eneris/push-receiver#15]
These endpoints will stop working next month:
const FCM_SUBSCRIBE = 'https://fcm.googleapis.com/fcm/connect/subscribe'
const FCM_ENDPOINT = 'https://fcm.googleapis.com/fcm/send'

https://firebase.google.com/support/faq#fcm-23-deprecation
https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by Eneris** [comment]
Thanks for bringing it up. I'll check out the upgrade posibility.
In mean time, feel free to add whatever you find. Thanks :)

**Comment by juangvega** [comment]
I found this. It is an upgraded version of MatthieuLemoine/push-receiver with the new endpoints.

https://github.com/MatthieuLemoine/push-receiver/compare/master...javajuice1337:push-receiver-v2:master

**Comment by Eneris** [comment]
Thanks for the detective. I'll attempt to transplant the changes within a few days and see if it works. Help is always appreciated :)

**Comment by Eneris** [comment]
It's looking good. Got a working version.
There are some new requests and token refreshing that needs to be done before releasing.
Also there are gonna be data changes so old tokens are probably gonna need to be re-generated

**Comment by Eneris** [comment]
@juangvega I've created a new version. Can you please double check form that is's working as expected?
https://www.npmjs.com/package/@eneris/push-receiver/v/4.0.0-beta

**Comment by juangvega** [comment]
Hi there! This is great news. I will try later and let you know. Thanks

**Comment by Eneris** [comment]
Seems to be working well

**Comment by tsightler** [comment]
@Eneris Thanks for your work on updating the FCM API.  I'm preparing to update ring-client-api which heavily depends on push-receiver, however, it's not clear to me what the upgrade/migration process from older versions might be.  Do I need to generate an FCM project for my specific project?

I'll try to look through the source code to get a better clue, but just doesn't feel very clear to me right now what `firebase` property should contain so if you have any hints it would be appreciated.

**Comment by Eneris** [comment]
> @Eneris Thanks for your work on updating the FCM API. I'm preparing to update ring-client-api which heavily depends on push-receiver, however, it's not clear to me what the upgrade/migration process from older versions might be. Do I need to generate an FCM project for my specific project?
> 
> I'll try to look through the source code to get a better clue, but just doesn't feel very clear to me right now what `firebase` property should contain so if you have any hints it would be appreciated.

Hi. Yea. The firebase project is required now (the free tier will do fine). Yasyest way is to copy-paste the config that firebase gives you for the web apps.
https://github.com/Eneris/push-receiver/blob/master/src/types.ts#L119-L128
These parts of the config are required
```TypeScript
{
    projectId: string
    appId: string
    apiKey: string
    messagingSenderId: string
}
```

As for migration steps:
* All that is required from your part is to supply new config properties
* PushReceiver will generate new credentials and tokens for each device automatically so save the new ones. The old ones will stop working since they are registered to old endpoints

**Comment by Eneris** [comment]
Web credentials for firebase are public so don't worry about compiling them into the code
