### ISSUE TITLE
Failure to receive messages after network connection outages

### ISSUE THREAD

**Issue by tsightler** [Eneris/push-receiver#28]
Hi @Eneris,

I've been having some random reports of users experiencing loss of push notifications after some time, it's been quite difficult to track down, but at least one case seems to be caused by loss of network connectivity as I can reproduce it fairly easily.  If you lose connectivity for more than a few minutes you will eventually get this message:

> TypeError: fetch failed
>     at node:internal/deps/undici/undici:12502:13
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async retry (/app/ring-mqtt/node_modules/@eneris/push-receiver/dist/utils/request.js:19:16)
>     at async checkIn (/app/ring-mqtt/node_modules/@eneris/push-receiver/dist/gcm.js:24:25)
>     at async PushReceiver.registerIfNeeded (/app/ring-mqtt/node_modules/@eneris/push-receiver/dist/client.js:147:13)
>     at async PushReceiver.connect (/app/ring-mqtt/node_modules/@eneris/push-receiver/dist/client.js:91:9)

If I understand the code flow correctly, and I may not, the retry logic is based on the websocket closing but I believe what is happening in this case:

1) Socket closes, which clears heartbeat handler and calls socketRetry()
2) socketRetry() calls destroy for previous socket, calls connect() with timeout
3) As shown in the stack trace, connect() calls registerIfNeeded() ==> checkIn(), which fails after 3 attempts (maxRetries) and throws the  error above.
4) So now, checkIn() still returns, even though it failed, but the new socket can't be established, and thus there are no more retries as a connection that is never established does not close.

I could probably address this as a client by monitoring for the code and implementing my own retry logic, but, based on the overall behavior, I'm assuming I should expect the recovery from this situation to be transparent for the consumer.

My first thought was to create a PR to write the request in checkIn, with it's own back-off retry, but it seems like the same logic is used for initial connection vs retry and you might want it to fail if it is initial connection so I wanted to bring your attention to the issue and get your feedback on how it should be addressed.

If you feel it should be addressed as a consumer, I'm find with that too, probably should just be documented that consumers should monitor for unrecoverable disconnection and implement their own recovery logic, but I think it might be a bit difficult to detect recoverable vs unrecoverable cases.

**Comment by Eneris** [comment]
Hi thanks for report.
Yes, you are right. The library should never stop trying to connect since the connectivity issue can be resolved at any time.

I'll attempt to fix this in the library

**Comment by tsightler** [comment]
Thanks @Eneris.  I'm happy to help out with testing or, if you have an idea of your preferred approach to fix this, I can try to put a PR together.  Initial thought was to modify the `#socketRetry()` function to await on connect() and retry if it fails, that way initial connects could still fail back to the client, but retries would attempt to reconnect forever.

**Comment by Eneris** [comment]
> Thanks @Eneris. I'm happy to help out with testing or, if you have an idea of your preferred approach to fix this, I can try to put a PR together. Initial thought was to modify the `#socketRetry()` function to await on connect() and retry if it fails, that way initial connects could still fail back to the client, but retries would attempt to reconnect forever.

That sounds like correct approach

**Comment by Eneris** [comment]
Just released version 4.3.0 with changes that address this issue
