### ISSUE TITLE
New token every App Launch.

### ISSUE THREAD

**Issue by bjsvedin** [Eneris/push-receiver#4]
I have implemented this library over the original to try and fix a bug where notifications stop working after some time. I am testing that now, but I noticed another item that I would like resolved. 

I get a new FCM token every single time I open up my electron application. Using a development build, or a production build, every time the application is closed all the way, then relaunched, the token that I get will be a new token. In every other use for FCM that I have implemented, the token will remain the same between launched unless a manual reset was done, or the app uninstalled and reinstalled. I have not implemented any resets in my code.

This is an issue because I track these, and I view them later for testing and general data gathering, but a new token every time will clutter my data.

I have looked into the library as best i could to determine if I am missing something in the setup/configuration, but I have not found anything I needed to do.

If you need anything from me to help resolve this let me know, I will get it for you.

**Comment by Eneris** [comment]
Hi. Thanks for reaching out.
You have to listen on credentials changes with `instance.onCredentialsChanged` and save them in your own storage. Then during the next launch, you need to supply them as property `credentials` to `new PushReceiver`

**Comment by Eneris** [comment]
Basically, any time `onCredentialsChanged` gets called, you save the result somewhere and supply them to constructor next time you run it as "initial data". Otherwise it won't have it and creates new one.

**Comment by bjsvedin** [comment]
I was able to make it work, thank you. I looked back at other implementations and I can see where they did the same thing, but I missed it before.
